# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_test_day2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Build Day 2
      run: |
        cd day2
        go build -v

    - name: Test Day 2
      run: |
        cd day2
        go test -v

  build_and_test_day3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Build Day 3
      run: |
        cd day3
        go build -v

    - name: Test Day 3
      run: |
        cd day3
        go test -v

  build_and_test_day4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Build Day 4
      run: |
        cd day4
        go build -v

    - name: Test Day 4
      run: |
        cd day4
        go test -v
